/*
 * sidevers.h — C bindings for the Sidevers protocol's core operations.
 *
 * Auto-generated by cbindgen; do not edit by hand.
 *
 * Memory ownership: any function that returns a heap-allocated buffer or
 * string transfers ownership to the caller. Release with the matching
 * sv_free_buffer / sv_free_string call. Buffers passed *in* are borrowed
 * and never freed by the FFI.
 *
 * Error reporting: functions return SvStatusOk (0) on success or a negative
 * status code on failure. After a failure, sv_last_error_message() may
 * return a heap-allocated UTF-8 string describing the cause (free with
 * sv_free_string).
 */


#ifndef SIDEVERS_H
#define SIDEVERS_H

/* WARNING: this file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Address kind tag for [`sv_address_encode`] / [`sv_address_decode`].
 */
enum SvAddressKind
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    /**
     * A side (sv1q…) — a person, or any addressable identity.
     */
    SvAddressKind_Side = 0,
    /**
     * A verse (svv1q…) — a shared space.
     */
    SvAddressKind_Verse = 1,
};
#ifndef __cplusplus
typedef uint8_t SvAddressKind;
#endif // __cplusplus

/**
 * FFI status codes. `SvStatus::Ok` is 0; all errors are negative integers.
 */
enum SvStatus
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    /**
     * Success.
     */
    SvStatus_Ok = 0,
    /**
     * A required pointer argument was null.
     */
    SvStatus_NullPtr = -1,
    /**
     * An input argument was malformed (wrong length, invalid UTF-8, etc.).
     */
    SvStatus_InvalidInput = -2,
    /**
     * A cryptographic operation failed (signature did not verify, decryption
     * failed, etc.).
     */
    SvStatus_Crypto = -3,
    /**
     * A decode operation failed (bad CBOR, bad bech32, etc.).
     */
    SvStatus_Decode = -4,
    /**
     * An internal invariant was violated. Indicates a bug.
     */
    SvStatus_Internal = -5,
    /**
     * The OS CSPRNG is unavailable.
     */
    SvStatus_CsprngUnavailable = -6,
    /**
     * A Rust panic was caught at the FFI boundary. Indicates a bug; the
     * process is in a defined state but the operation did not complete.
     * (Audit P1.B: panics that unwind across a C-ABI boundary are UB; this
     * status lets the caller see the failure instead of corrupting state.)
     */
    SvStatus_Panic = -7,
};
#ifndef __cplusplus
typedef int32_t SvStatus;
#endif // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Encode a 32-byte Ed25519 public key as a bech32m Sidevers address.
 *
 * `pubkey_32` MUST point to a 32-byte buffer. Returns a heap-allocated
 * NUL-terminated C string (`sv1q…` for sides, `svv1q…` for verses); free
 * with [`sv_free_string`](crate::sv_free_string). Returns null on error.
 */
char *sv_address_encode(const uint8_t *pubkey_32, SvAddressKind kind);

/**
 * Parse a bech32m address into its 32-byte public key + kind.
 *
 * `addr` MUST be a NUL-terminated UTF-8 C string. `out_pubkey_32` MUST
 * point to a writable 32-byte buffer. `out_kind` MUST point to a writable
 * `SvAddressKind`. On error, both outputs are left untouched.
 */
SvStatus sv_address_decode(const char *addr,
                           uint8_t *out_pubkey_32,
                           SvAddressKind *out_kind);

/**
 * Encode a contact-card invite URI (`sidevers-contact:1:<base32>`).
 *
 * Inputs:
 *   * `side_32` — the inviter's side public key (Ed25519, 32 bytes). Required.
 *   * `dial_addr` — NUL-terminated UTF-8 host:port the friend's client should dial
 *     (e.g. `"203.0.113.5:4242"`). Required, 1–256 bytes.
 *   * `display_name` — NUL-terminated UTF-8 hint shown on first encounter, or
 *     `NULL` to omit. Max 512 bytes.
 *   * `side_label` — NUL-terminated UTF-8 context hint (e.g. `"work"`), or
 *     `NULL` to omit. Max 64 bytes.
 *
 * Output:
 *   * `*out_uri` — heap-allocated NUL-terminated C string. Free with
 *     [`sv_free_string`](crate::sv_free_string).
 */
SvStatus sv_contact_card_encode(const uint8_t *side_32,
                                const char *dial_addr,
                                const char *display_name,
                                const char *side_label,
                                char **out_uri);

/**
 * Parse a contact-card invite URI back into its fields.
 *
 * Inputs:
 *   * `uri` — NUL-terminated UTF-8 `"sidevers-contact:1:<base32>"`.
 *
 * Outputs (all required pointers):
 *   * `out_side_32` — writable 32-byte buffer for the inviter's side pubkey.
 *   * `*out_dial_addr` — heap-allocated NUL-terminated C string, always set on success.
 *   * `*out_display_name` — heap-allocated NUL-terminated C string, OR `NULL` if the
 *     URI did not include a display name.
 *   * `*out_side_label` — heap-allocated NUL-terminated C string, OR `NULL` if the
 *     URI did not include a side label.
 *
 * Each non-NULL returned string must be freed with [`sv_free_string`](crate::sv_free_string).
 * On error, no outputs are modified.
 */
SvStatus sv_contact_card_parse(const char *uri,
                               uint8_t *out_side_32,
                               char **out_dial_addr,
                               char **out_display_name,
                               char **out_side_label);

/**
 * Build a signed, encrypted DirectMessage envelope ready for the wire.
 *
 * Inputs:
 *   * `sender_seed_32` — sender's side seed (32 bytes).
 *   * `recipient_pubkey_32` — recipient's side public key (32 bytes).
 *   * `text_utf8`, `text_len` — the message body. Must be valid UTF-8.
 *
 * On success, `*out_wire_ptr` is set to a heap-allocated buffer of length
 * `*out_wire_len`. Free with [`sv_free_buffer`](crate::sv_free_buffer).
 */
SvStatus sv_dm_seal_text(const uint8_t *sender_seed_32,
                         const uint8_t *recipient_pubkey_32,
                         const uint8_t *text_utf8,
                         uintptr_t text_len,
                         uint8_t **out_wire_ptr,
                         uintptr_t *out_wire_len);

/**
 * Verify, decrypt, and extract the plaintext body of a DirectMessage
 * envelope addressed to this side.
 *
 * Inputs:
 *   * `recipient_seed_32` — this side's seed (32 bytes).
 *   * `wire_ptr`, `wire_len` — the envelope bytes received over the wire.
 *
 * Outputs:
 *   * `*out_text_ptr` / `*out_text_len` — the decoded plaintext (heap-
 *     allocated; free with [`sv_free_buffer`](crate::sv_free_buffer)).
 *   * `out_sender_pubkey_32` — the sender's side public key (the envelope's
 *     `from` field). MUST point to a writable 32-byte buffer.
 *
 * Returns `SvStatus::Crypto` if the signature or decryption fails;
 * `SvStatus::InvalidInput` if the envelope isn't a text DirectMessage
 * addressed to this side.
 */
SvStatus sv_dm_open_text(const uint8_t *recipient_seed_32,
                         const uint8_t *wire_ptr,
                         uintptr_t wire_len,
                         uint8_t *out_sender_pubkey_32,
                         uint8_t **out_text_ptr,
                         uintptr_t *out_text_len);

/**
 * Retrieve the last error message for the current thread, if any.
 *
 * Returns a heap-allocated UTF-8 C string (NUL-terminated). Caller MUST
 * free it with [`sv_free_string`](crate::sv_free_string). Returns null
 * if there is no error.
 */
char *sv_last_error_message(void);

/**
 * Generate a fresh master seed from the OS CSPRNG.
 *
 * `out_seed_32` MUST point to a writable 32-byte buffer. On success the
 * buffer is filled with the master seed (the user's identity root — keep
 * this private).
 */
SvStatus sv_keygen_master(uint8_t *out_seed_32);

/**
 * Derive a side keypair from a master seed under the given UTF-8 label.
 *
 * `master_seed_32` MUST point to a 32-byte buffer. `label` MUST be a
 * NUL-terminated UTF-8 string. `out_side_seed_32` MUST point to a writable
 * 32-byte buffer.
 */
SvStatus sv_derive_side(const uint8_t *master_seed_32,
                        const char *label,
                        uint8_t *out_side_seed_32);

/**
 * Compute the public key for an Ed25519 seed (works for master, side, or
 * verse keypairs — they all share the same key space).
 *
 * `seed_32` MUST point to a 32-byte buffer. `out_pubkey_32` MUST point to
 * a writable 32-byte buffer.
 */
SvStatus sv_pubkey_from_seed(const uint8_t *seed_32, uint8_t *out_pubkey_32);

/**
 * Sign a fresh linkage proof binding `side_a` and `side_b` (both belonging
 * to the caller). On success returns the wire bytes — a CBOR record both
 * sides have signed, verifiable by anyone holding it.
 *
 * Inputs:
 *   * `side_a_seed_32`, `side_b_seed_32` — the two side seeds (32 bytes each).
 *   * `issued_at` — unix seconds timestamp.
 *
 * Outputs:
 *   * `*out_wire_ptr` / `*out_wire_len` — heap-allocated wire bytes; free
 *     with [`sv_free_buffer`](crate::sv_free_buffer).
 */
SvStatus sv_linkage_sign(const uint8_t *side_a_seed_32,
                         const uint8_t *side_b_seed_32,
                         uint64_t issued_at,
                         uint8_t **out_wire_ptr,
                         uintptr_t *out_wire_len);

/**
 * Verify a linkage-proof wire encoding and extract the two side public
 * keys and the issued-at timestamp.
 *
 * Inputs:
 *   * `wire_ptr`, `wire_len` — the proof bytes.
 *
 * Outputs:
 *   * `out_side_a_32`, `out_side_b_32` — writable 32-byte buffers.
 *   * `out_issued_at` — writable u64.
 */
SvStatus sv_linkage_verify(const uint8_t *wire_ptr,
                           uintptr_t wire_len,
                           uint8_t *out_side_a_32,
                           uint8_t *out_side_b_32,
                           uint64_t *out_issued_at);

/**
 * Release a buffer previously returned by a Sidevers FFI function.
 *
 * `ptr` MUST be the value originally returned by Sidevers, paired with the
 * `len` returned alongside it. Calling with mismatched arguments is
 * undefined behavior. A null pointer or zero length is a no-op.
 */
void sv_free_buffer(uint8_t *ptr, uintptr_t len);

/**
 * Release a NUL-terminated C string previously returned by a Sidevers FFI
 * function.
 *
 * `ptr` MUST be the value originally returned by Sidevers (e.g. by
 * `sv_address_encode` or `sv_last_error_message`). A null pointer is a no-op.
 */
void sv_free_string(char *ptr);

/**
 * Verify a `HandleAttestPayload` wire encoding and extract the side
 * public key, the claimed handle, the registry's domain, and the
 * issued-at timestamp.
 *
 * Stage E (federated-handle-namespace migration): the domain is now
 * a separate signed field. The full display form is
 * `<handle_local>@<domain>`; callers compose it themselves so they
 * don't accidentally trust a registry that's serving a domain it
 * doesn't own.
 *
 * Inputs:
 *   * `wire_ptr`, `wire_len` — the CBOR-encoded HandleAttest bytes.
 *
 * Outputs (all required):
 *   * `out_side_pk_32` — writable 32-byte buffer for the claiming side's pubkey.
 *   * `*out_handle_local` — heap-allocated NUL-terminated C string with
 *     the local part (the bit before the `@`). Free with
 *     [`sv_free_string`](crate::sv_free_string).
 *   * `*out_domain` — heap-allocated NUL-terminated C string with the
 *     issuing registry's domain. Free with
 *     [`sv_free_string`](crate::sv_free_string).
 *   * `out_issued_at` — writable u64.
 *
 * On error, no outputs are modified and any partially allocated
 * strings are freed before returning.
 */
SvStatus sv_handle_attest_verify(const uint8_t *wire_ptr,
                                 uintptr_t wire_len,
                                 uint8_t *out_side_pk_32,
                                 char **out_handle_local,
                                 char **out_domain,
                                 uint64_t *out_issued_at);

/**
 * Verify a `PagePublishPayload` wire encoding and extract the side public
 * key, slug, MIME type, content bytes, and published-at timestamp.
 *
 * Inputs:
 *   * `wire_ptr`, `wire_len` — the CBOR-encoded PagePublish bytes.
 *
 * Outputs (all required):
 *   * `out_side_pk_32` — writable 32-byte buffer for the publishing side.
 *   * `*out_slug` — heap-allocated NUL-terminated C string with the slug.
 *     Free with [`sv_free_string`](crate::sv_free_string).
 *   * `*out_mime` — heap-allocated NUL-terminated C string with the MIME.
 *     Free with [`sv_free_string`](crate::sv_free_string).
 *   * `*out_content_ptr` / `*out_content_len` — heap-allocated content
 *     bytes. Free with [`sv_free_buffer`](crate::sv_free_buffer).
 *   * `out_published_at` — writable u64.
 *
 * On error, no outputs are modified and any partially allocated buffers
 * are freed before returning.
 */
SvStatus sv_page_publish_verify(const uint8_t *wire_ptr,
                                uintptr_t wire_len,
                                uint8_t *out_side_pk_32,
                                char **out_slug,
                                char **out_mime,
                                uint8_t **out_content_ptr,
                                uintptr_t *out_content_len,
                                uint64_t *out_published_at);

/**
 * Verify a 64-byte Ed25519 signature against a 32-byte public key and an
 * arbitrary message. Returns `SvStatus::Ok` if the signature verifies,
 * `SvStatus::Crypto` if it doesn't, `SvStatus::Decode` if the public key
 * is not a valid Ed25519 point.
 *
 * This is the thin wrapper used by the Laravel paired-device sign-in flow
 * to verify a side's signature over an auth challenge. The challenge
 * message itself is constructed PHP-side; this function only checks the
 * math.
 */
SvStatus sv_verify_signature(const uint8_t *pubkey_32,
                             const uint8_t *msg_ptr,
                             uintptr_t msg_len,
                             const uint8_t *sig_64);

/**
 * Compute a 32-byte BLAKE3 hash of an arbitrary message. Used by the
 * Laravel registry as a content-address for HTTP ETag caching — the
 * same hash function the protocol uses for canonical signing, so a
 * page's BLAKE3 is stable across re-encodings.
 *
 * Inputs:
 *   * `msg_ptr` / `msg_len` — the bytes to hash.
 *
 * Output:
 *   * `out_hash_32` — writable 32-byte buffer.
 */
SvStatus sv_blake3(const uint8_t *msg_ptr, uintptr_t msg_len, uint8_t *out_hash_32);

/**
 * Compose a `DirectoryEntryPayload` for a single handle from its parts.
 *
 * The registry stores claimed handles with their already-signed
 * `HandleAttest` wire bytes; this function takes that wire (plus the
 * side pubkey and handle for redundant validation) and produces the
 * canonical CBOR encoding the registry serves at
 * `/.well-known/sidevers/resolve/{handle}`.
 *
 * Inputs:
 *   * `side_pk_32` — the 32-byte side public key that owns the handle.
 *   * `handle` — NUL-terminated UTF-8 handle string.
 *   * `attestation_wire_ptr` / `attestation_wire_len` — the signed
 *     `HandleAttestPayload` bytes (will be verified before composition).
 *
 * Outputs:
 *   * `*out_wire_ptr` / `*out_wire_len` — heap-allocated CBOR bytes;
 *     free with [`sv_free_buffer`](crate::sv_free_buffer).
 */
SvStatus sv_directory_entry_encode(const uint8_t *side_pk_32,
                                   const char *handle,
                                   const uint8_t *attestation_wire_ptr,
                                   uintptr_t attestation_wire_len,
                                   uint8_t **out_wire_ptr,
                                   uintptr_t *out_wire_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SIDEVERS_H */
